### ISSUE TITLE
Error Parse Environment Variable for WhatsApp Client Datastore Type exit status 1

### ISSUE THREAD

**Issue by davinderSingh1** [dimaskiddo/go-whatsapp-multidevice-rest#10]
FATA[2022-05-08T14:56:23+05:30] [Error Parse Environment Variable for WhatsApp Client Datastore Type
exit status 1
![eee](https://user-images.githubusercontent.com/78996662/167290223-d8dfe2e4-b32c-4a39-813f-f18440faedf7.PNG)
]

**Comment by dimaskiddo** [comment]
Please read carefully the instruction you need .env file which can a copy of .env.default, .env.production, .env.development
In the instruction you need to soft link the .env.development as .env file using ln command

I'll close this issue since it's problem on your side while running the instructions
By the way if you just need the precompiled version please check the [releases page](https://github.com/dimaskiddo/go-whatsapp-multidevice-rest/releases)
